name: CI
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: printing name
        run: echo "Shankar"
      - name: printing date
        run: date
      - name: printing git var
        run: echo "${{ runner.os }}"
      - name: print workflow event
        run: echo "${{github.event_name}}"
        
