name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: printing name
        run: echo "Shankar"
      - name: printing date
        run: date
      - name: printing git var
        run: echo "${{runnner.os}}"
