name: CI
on: pull_request
env:
  APP_ENV: production
  Log_Level: debug
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: printing name
        run: echo "Shankar Jha"
      - name: printing date
        run: date
      - name: printing git var
        run: echo "${{ runner.os }}"
      - name: print workflow event
        run: echo "${{github.event_name}}"
      - name: printing env var
        run: echo " $APP_ENV $Log_Level"
        
