name: CI
on: push
env:
  APP_ENV: production
  Log_Level: debug
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: printing name
        run: echo "Shankar Jha"
      - name: printing date
        run: date
      - name: printing git var
        run: echo "${{ runner.os }}"
      - name: print workflow event
        run: echo "${{github.event_name}}"
      - name: printing env var
        run: |
           echo "${{APP_ENV}} ${{LOG_LEVEL}}"
        
