name: multijob
on: push
jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: echo firstname
              run: ech"shankar"
    job2:
        needs: job1
        runs-on: ubuntu-latest
        steps:
            - name: echo lastname
              run: echo "jha"